version: '3'
services:
  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=RohrKabel06
      - MYSQL_DATABASE=biketracker

  backend:
    build: ./backend
    image: ntrappregistry.azurecr.io/backend
    container_name: backend
    ports:
      - "8080:8080"
      - "9092:9092"
    depends_on:
      - database

  # React Frontend Service
  frontend:
    build: ./frontend
    image: ntrappregistry.azurecr.io/frontend
    container_name: frontend
    ports:
      - "3000:3000"
    links:
      - backend
